import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import {images} from '../data/site.mjs';
const root=path.resolve(import.meta.dirname,'..'),data=path.join(root,'data'),dest=path.join(root,'public/assets/source');fs.mkdirSync(dest,{recursive:true});
const read=(f,fallback)=>{try{return JSON.parse(fs.readFileSync(path.join(data,f),'utf8'))}catch{return fallback}};
const catalog=read('catalog.json',[]),blog=read('blog.json',{articles:[]}),map=read('asset-map.json',{});
const urls=[...new Set([...Object.values(images),...catalog.flatMap(p=>[p.image,...(p.images||[])]),...blog.articles.map(p=>p.image),...Array.from({length:10},(_,i)=>`https://yardstopinc.com/wp-content/uploads/Flwers-${i+1}-300x300.jpg`)].filter(x=>x&&x.startsWith('https://yardstopinc.com/wp-content/uploads/')))];
const failures=[];let index=0,success=0;const limit=16*1024*1024;
async function download(url){const r=await fetch(url,{signal:AbortSignal.timeout(20000),redirect:'follow'});if(!r.ok)throw Error('HTTP '+r.status);if(new URL(r.url).hostname!=='yardstopinc.com')throw Error('Unexpected host redirect');const type=r.headers.get('content-type')||'';if(!type.startsWith('image/'))throw Error('Not an image');const declared=Number(r.headers.get('content-length')||0);if(declared>limit)throw Error('Image too large');const reader=r.body.getReader();let length=0,chunks=[];while(true){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>limit){await reader.cancel();throw Error('Image too large')}chunks.push(Buffer.from(value))}return {bytes:Buffer.concat(chunks),type};}
async function worker(){while(index<urls.length){const url=urls[index++];if(map[url]&&fs.existsSync(path.join(root,'public',map[url]))){success++;continue}const full=url.replace(/-\d+x\d+(?=\.(?:jpe?g|png|webp)$)/i,'');let result;try{try{result=await download(full)}catch(err){if(full===url)throw err;result=await download(url)}const ext={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','image/gif':'.gif','image/svg+xml':'.svg'}[result.type.split(';')[0]]||path.extname(new URL(url).pathname);const name=crypto.createHash('sha256').update(url).digest('hex').slice(0,16)+ext;fs.writeFileSync(path.join(dest,name),result.bytes);map[url]='/assets/source/'+name;success++}catch(err){failures.push({url,error:err.message})}fs.writeFileSync(path.join(data,'asset-map.json'),JSON.stringify(map,null,2))}}
await Promise.all(Array.from({length:4},worker));fs.writeFileSync(path.join(data,'asset-download-report.json'),JSON.stringify({success,failures},null,2));console.log(`${success}/${urls.length} image assets saved. ${failures.length} need review. Rebuild with npm run build.`);if(failures.length)process.exitCode=1;
