import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),dist=path.join(root,'dist'),output=path.resolve(process.env.PREVIEW_OUTPUT_DIR || path.join(root,'outputs'));
const read=f=>fs.readFileSync(path.join(dist,f),'utf8');const json=s=>JSON.stringify(s).replace(/</g,'\\u003c');
const assetMapPath=path.join(root,'data/asset-map.json');
const assetMap=fs.existsSync(assetMapPath)?JSON.parse(fs.readFileSync(assetMapPath,'utf8')):{};
const routes=JSON.parse(read('routes.json'));const pages={};const hero='data:image/jpeg;base64,'+fs.readFileSync(path.join(dist,'assets/garden-hero.jpg')).toString('base64');
const withHero=s=>s.replaceAll('/assets/garden-hero.jpg',hero);
for(const route of routes){const html=read(path.join(route.path,'index.html'));pages[route.path]={title:route.title,body:html.match(/<main id="main">([\s\S]*?)<\/main>/)[1]};}
const homepage=read('index.html'),bodyStart=homepage.match(/<body[^>]*>([\s\S]*?)<main id="main">/)[1],bodyEnd=homepage.match(/<\/main>([\s\S]*?)<\/body>/)[1];
let app=read('app.js').replace('(() => {','window.YardStopInit = () => {').replace(/\}\)\(\);\s*$/,'};');
app=app.replace("const res=await fetch('/data/search.json');if(!res.ok)throw Error();searchData=await res.json();","searchData=window.YardStopData.search;");
app=app.replace("new URLSearchParams(location.search)","new URLSearchParams(new URL(window.YardStopRoute,'https://preview.local').search)");
app=app.replace("history.replaceState(null,'',location.pathname+(params.size?'?'+params:''))","window.replacePreviewQuery(params)");
app=app.replace("fetch('/data/catalog.json').then(res=>{if(!res.ok)throw Error();return res.json()})","Promise.resolve(window.YardStopData.catalog)");
const script=`window.YardStopData={catalog:${read('data/catalog.json')},search:${read('data/search.json')}};const pages=${json(pages)};const header=${json(bodyStart)};const footer=${json(bodyEnd)};const hero=${json(hero)};${app}\nwindow.replacePreviewQuery=function(params){const url=new URL(window.YardStopRoute,'https://preview.local');window.YardStopRoute=url.pathname+(params.size?'?'+params:'');try{history.replaceState(null,'','#'+window.YardStopRoute)}catch{}};function navigate(route,update=true){const u=new URL(route,'https://preview.local');const key=u.pathname.endsWith('/')?u.pathname:u.pathname+'/';const p=pages[key]||pages['/'];window.YardStopRoute=key+u.search;document.title=p.title+' | The Yard Stop';document.body.classList.remove('locked');document.body.innerHTML=(header+'<main id="main">'+p.body+'</main>'+footer).replaceAll('/assets/garden-hero.jpg',hero);if(update){try{history.pushState(null,'','#'+window.YardStopRoute)}catch{}}window.YardStopInit();window.scrollTo(0,0);if(u.hash){requestAnimationFrame(()=>document.getElementById(u.hash.slice(1))?.scrollIntoView())}}document.addEventListener('click',ev=>{const a=ev.target.closest('a');if(!a||ev.metaKey||ev.ctrlKey||ev.shiftKey||ev.altKey)return;const href=a.getAttribute('href');if(href&&href.startsWith('/')&&!href.startsWith('//')){ev.preventDefault();navigate(href)}});window.addEventListener('popstate',()=>navigate(location.hash.slice(1)||'/',false));navigate(location.hash.startsWith('#/')?location.hash.slice(1):'/',false);`;
const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>The Yard Stop Design Preview</title><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;450;500;550;600;650;700&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet"><style>'+read('styles.css')+'</style></head><body>'+withHero(bodyStart+`<main id="main">${pages['/'].body}</main>`+bodyEnd)+'<script>'+script.replace(/<\/script/gi,'<\\/script')+'</script></body></html>';
const portableHtml=Object.entries(assetMap).reduce((document,[original,local])=>document.replaceAll(local,original),html);
fs.mkdirSync(output,{recursive:true});const destination=path.join(output,'Yard-Stop-Preview.html');fs.writeFileSync(destination,portableHtml);console.log(destination+' ('+(portableHtml.length/1024/1024).toFixed(2)+' MB)');
